#ifndef GAMEPROP_H
#define GAMEPROP_H

#define START_POINT 0, 0
#define DEFAULT_PLAYER_POS 500
#define PLAY_BUTTON_POS 300, 450
#define EXIT_BUTTON_POS 500, 450
#define SETTING_BUTTON_POS 700, 450
#define HIGHSCORE_BUTTON_POS 900, 450
#define CONTINUE_BUTTON_POS 480, 320
#define HOME_BUTTON_POS 750, 320
#define RETRY_BUTTON_POS 400, 320
#define MUSIC_BUTTON_POS 620, 320

#define DELAY_CONSTANT 50
#define CHARACTER_DELAY 8
#define EXPLOSION_DELAY 10
#define SWORD_DELAY_FRAME 12
#define MAX_HEAL 4

#define HEART_PROPS 0, 669, 51, 51
#define SWORD_PROPS 200, 656, 64, 64
#define GAME_TITLE_PROPS 120, 40, 1050, 350
#define GHOSTBALL_SIZE 56, 56
#define SHIELD_SIZE 175
#define TIME_SHOW_SIZE 64
#define SWORD_TAIL_WIDTH 45
#define SWORD_TAIL_HEIGHT 90
#define BUTTON_SIZE 64
#define GAME_TITLE_WIDTH 800
#define GAME_TITLE_HEIGHT 250
#define SPAN_WIDTH 1120	
#define SPAN_HEIGHT	480
#define GAME_END_WIDTH 550
#define GAME_END_HEIGHT 180

#define GET_CENTER_SHIELD_X 65
#define GET_CENTER_SHIELD_Y 70 

#define ACC_PLAYER_X  7.f
#define ACC_PLAYER_Y  -15.f

#define VEL_PLAYER_START 0.f
#define TIME_TO_SEC 1000.f

#define INCREASE_SPEED_TIME 7000
#define SWORD_COOLDOWN_TIME 4000
#define SHIELD_TIME 5000

#define BACK_FROM_HELL 3000
const int SCREEN_WIDTH = 1260;
const int SCREEN_HEIGHT = 720;

const int SOLID_FLOOR = 640;
const int DELAY = 50;

const int WAITFORCALL = -150;

// for player
const int FRAME_SIZE = 180;

const int PLAYER_WIDTH = 30;
const int PLAYER_HEIGHT = 45;

const int GRAVITY = 1;
const int IDLE_FRAMES = 10;
const int JUMP_FRAMES = 2;
const int RUN_FRAMES = 7;
const int DEATH_FRAMES = 10;

const int HEART_SIZE = 17;

//ghost
const int BOUND_DISTANCE = 300;
const int GHOST_FLY_FRAME = 6;
const int GHOST_DEATH_FRAME = 5;
const int GHOST_WIDTH = 64;
const int GHOST_HEIGHT = 44;

//enemy
const int EXPLOSION_SIZE = 96;
const int GHOSTBALL_FRAMES = 4;
const int EXPLOSION_FRAMES = 11;

// sword
const int SWORD_TAIL_FRAMES = 8;

// heart
const int HEART_FRAME = 4;
enum {
	GAME_MENU,
	GAME_PLAY,
	GAME_END,
	GAME_PAUSE, 
	GAME_HIGHSCORE,
};
#endif // GAMEPROP_H
